server:
  port: 8081

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:sqlite:/data/auth.db
    driver-class-name: org.sqlite.JDBC
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update
    show-sql: false
  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}

jwt:
  secret: ${JWT_SECRET:supersecretkeymustbe32charslong!!}
  access-expiration: 1800000
  refresh-expiration: 604800000
