server:
  port: 8082

spring:
  application:
    name: menu-service
  datasource:
    url: jdbc:sqlite:/data/menu.db
    driver-class-name: org.sqlite.JDBC
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update
    show-sql: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
