server:
  port: 8084

spring:
  application:
    name: review-service
  datasource:
    url: jdbc:sqlite:/data/review.db
    driver-class-name: org.sqlite.JDBC
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update
    show-sql: false
